version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - PINECONE_API_KEY=${PINECONE_API_KEY}
        - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
        - PINECONE_INDEX_TWO=${PINECONE_INDEX_TWO}
        - PINECONE_NAMESPACE=${PINECONE_NAMESPACE}
        - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
        - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
        - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_TWO=${PINECONE_INDEX_TWO}
      - PINECONE_NAMESPACE=${PINECONE_NAMESPACE}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    restart: always 